FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install any system dependencies needed for building Python packages
# For example, 'gcc' or 'libffi-dev' if your packages need C libraries.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      gcc \
      libffi-dev \
      git \
      && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir tox twine
